<?php
header('Content-Type: text/plain; charset=utf-8');
// migrate.php
include 'db.php';
include 'fungsi.php';

try {
    $mysqlConn = getMySQLConnection();
    $sqlServerConn = getSQLServerConnection();

    $sql = "SELECT count(ot_id) FROM t_overtime";
    $stmt = $mysqlConn->prepare($sql);
    $stmt->execute();

    $total_data = $stmt->fetchColumn();
    $offset = 0;
    $limit = 10000;
    $current_id = 0;
    
    while($offset < $total_data):

        // Fetch data from MySQL
        $query = $mysqlConn->query("SELECT * FROM t_overtime LIMIT $limit OFFSET $offset");
        $data = $query->fetchAll(PDO::FETCH_ASSOC);

        // Prepare SQL Server upsert statement
        $upsertQuery = "
            SET IDENTITY_INSERT Hris_TOvertime ON; -- Enable identity insert

            MERGE INTO Hris_TOvertime AS target
            USING (
                SELECT 
                    :ot_id AS ot_id, 
                    :ot_date AS ot_date, 
                    :mk_nopeg AS mk_nopeg,
                    :ot_begin AS ot_begin,
                    :ot_end AS ot_end,
                    :ot_end_sap AS ot_end_sap,
                    :kuota_terpakai_sp AS kuota_terpakai_sp,
                    :ot_wo_break AS ot_wo_break,
                    :ot_wo_break_begin AS ot_wo_break_begin,
                    :ot_wo_break_end AS ot_wo_break_end,
                    :ot_ti1_status AS ot_ti1_status,
                    :ot_ti1_begin AS ot_ti1_begin,
                    :ot_ti1_end AS ot_ti1_end,
                    :ot_wo_break2 AS ot_wo_break2,
                    :ot_wo_break2_begin AS ot_wo_break2_begin,
                    :ot_wo_break2_end AS ot_wo_break2_end,
                    :ot_ti2_status AS ot_ti2_status,
                    :ot_ti2_begin AS ot_ti2_begin,
                    :ot_ti2_end AS ot_ti2_end,
                    :ot_wo_break3 AS ot_wo_break3,
                    :ot_wo_break3_begin AS ot_wo_break3_begin,
                    :ot_wo_break3_end AS ot_wo_break3_end,
                    :ot_ti3_status AS ot_ti3_status,
                    :ot_ti3_begin AS ot_ti3_begin,
                    :ot_ti3_end AS ot_ti3_end,
                    :ot_notes AS ot_notes,
                    :ot_app1_unit AS ot_app1_unit,
                    :ot_app1_by AS ot_app1_by,
                    :ot_app1_time AS ot_app1_time,
                    :ot_app1_status AS ot_app1_status,
                    :ot_app2_unit AS ot_app2_unit,
                    :ot_app2_by AS ot_app2_by,
                    :ot_app2_time AS ot_app2_time,
                    :ot_app2_status AS ot_app2_status,
                    :ot_app3_unit AS ot_app3_unit,
                    :ot_app3_by AS ot_app3_by,
                    :ot_app3_time AS ot_app3_time,
                    :ot_app3_status AS ot_app3_status,
                    :ot_meal1_take_by AS ot_meal1_take_by,
                    :ot_meal1_take_time AS ot_meal1_take_time,
                    :ot_meal1_take_status AS ot_meal1_take_status,
                    :ot_meal1_give_by AS ot_meal1_give_by,
                    :ot_meal1_give_time AS ot_meal1_give_time,
                    :ot_meal1_give_status AS ot_meal1_give_status,
                    :ot_meal1_take_by2 AS ot_meal1_take_by2,
                    :ot_meal1_rpt AS ot_meal1_rpt,
                    :ot_meal2_take_by AS ot_meal2_take_by,
                    :ot_meal2_take_time AS ot_meal2_take_time,
                    :ot_meal2_take_status AS ot_meal2_take_status,
                    :ot_meal2_give_by AS ot_meal2_give_by,
                    :ot_meal2_give_time AS ot_meal2_give_time,
                    :ot_meal2_give_status AS ot_meal2_give_status,
                    :ot_meal2_take_by2 AS ot_meal2_take_by2,
                    :ot_meal2_rpt AS ot_meal2_rpt,
                    :ot_meal3_take_by AS ot_meal3_take_by,
                    :ot_meal3_take_time AS ot_meal3_take_time,
                    :ot_meal3_take_status AS ot_meal3_take_status,
                    :ot_meal3_give_by AS ot_meal3_give_by,
                    :ot_meal3_give_time AS ot_meal3_give_time,
                    :ot_meal3_give_status AS ot_meal3_give_status,
                    :ot_meal3_take_by2 AS ot_meal3_take_by2,
                    :ot_meal3_rpt AS ot_meal3_rpt,
                    :ot_create AS ot_create,
                    :ot_createby AS ot_createby,
                    :ot_update AS ot_update,
                    :ot_updateby AS ot_updateby,
                    :status AS status,
                    :koreksi AS koreksi,
                    :kunci AS kunci,
                    :status_sap AS status_sap,
                    :del_flag AS del_flag,
                    :del_time AS del_time,
                    :del_by AS del_by,
                    :status_delsap AS status_delsap,
                    :otc_id AS otc_id
            ) AS source
            ON target.ot_id = source.ot_id
            WHEN MATCHED THEN
                UPDATE SET 
                    target.ot_date = source.ot_date, 
                    target.mk_nopeg = source.mk_nopeg,
                    target.ot_begin = source.ot_begin,
                    target.ot_end = source.ot_end,
                    target.ot_end_sap = source.ot_end_sap,
                    target.kuota_terpakai_sp = source.kuota_terpakai_sp,
                    target.ot_wo_break = source.ot_wo_break,
                    target.ot_wo_break_begin = source.ot_wo_break_begin,
                    target.ot_wo_break_end = source.ot_wo_break_end,
                    target.ot_ti1_status = source.ot_ti1_status,
                    target.ot_ti1_begin = source.ot_ti1_begin,
                    target.ot_ti1_end = source.ot_ti1_end,
                    target.ot_wo_break2 = source.ot_wo_break2,
                    target.ot_wo_break2_begin = source.ot_wo_break2_begin,
                    target.ot_wo_break2_end = source.ot_wo_break2_end,
                    target.ot_ti2_status = source.ot_ti2_status,
                    target.ot_ti2_begin = source.ot_ti2_begin,
                    target.ot_ti2_end = source.ot_ti2_end,
                    target.ot_wo_break3 = source.ot_wo_break3,
                    target.ot_wo_break3_begin = source.ot_wo_break3_begin,
                    target.ot_wo_break3_end = source.ot_wo_break3_end,
                    target.ot_ti3_status = source.ot_ti3_status,
                    target.ot_ti3_begin = source.ot_ti3_begin,
                    target.ot_ti3_end = source.ot_ti3_end,
                    target.ot_notes = source.ot_notes,
                    target.ot_app1_unit = source.ot_app1_unit,
                    target.ot_app1_by = source.ot_app1_by,
                    target.ot_app1_time = source.ot_app1_time,
                    target.ot_app1_status = source.ot_app1_status,
                    target.ot_app2_unit = source.ot_app2_unit,
                    target.ot_app2_by = source.ot_app2_by,
                    target.ot_app2_time = source.ot_app2_time,
                    target.ot_app2_status = source.ot_app2_status,
                    target.ot_app3_unit = source.ot_app3_unit,
                    target.ot_app3_by = source.ot_app3_by,
                    target.ot_app3_time = source.ot_app3_time,
                    target.ot_app3_status = source.ot_app3_status,
                    target.ot_meal1_take_by = source.ot_meal1_take_by,
                    target.ot_meal1_take_time = source.ot_meal1_take_time,
                    target.ot_meal1_take_status = source.ot_meal1_take_status,
                    target.ot_meal1_give_by = source.ot_meal1_give_by,
                    target.ot_meal1_give_time = source.ot_meal1_give_time,
                    target.ot_meal1_give_status = source.ot_meal1_give_status,
                    target.ot_meal1_take_by2 = source.ot_meal1_take_by2,
                    target.ot_meal1_rpt = source.ot_meal1_rpt,
                    target.ot_meal2_take_by = source.ot_meal2_take_by,
                    target.ot_meal2_take_time = source.ot_meal2_take_time,
                    target.ot_meal2_take_status = source.ot_meal2_take_status,
                    target.ot_meal2_give_by = source.ot_meal2_give_by,
                    target.ot_meal2_give_time = source.ot_meal2_give_time,
                    target.ot_meal2_give_status = source.ot_meal2_give_status,
                    target.ot_meal2_take_by2 = source.ot_meal2_take_by2,
                    target.ot_meal2_rpt = source.ot_meal2_rpt,
                    target.ot_meal3_take_by = source.ot_meal3_take_by,
                    target.ot_meal3_take_time = source.ot_meal3_take_time,
                    target.ot_meal3_take_status = source.ot_meal3_take_status,
                    target.ot_meal3_give_by = source.ot_meal3_give_by,
                    target.ot_meal3_give_time = source.ot_meal3_give_time,
                    target.ot_meal3_give_status = source.ot_meal3_give_status,
                    target.ot_meal3_take_by2 = source.ot_meal3_take_by2,
                    target.ot_meal3_rpt = source.ot_meal3_rpt,
                    target.ot_create = source.ot_create,
                    target.ot_createby = source.ot_createby,
                    target.ot_update = source.ot_update,
                    target.ot_updateby = source.ot_updateby,
                    target.status = source.status,
                    target.koreksi = source.koreksi,
                    target.kunci = source.kunci,
                    target.status_sap = source.status_sap,
                    target.del_flag = source.del_flag,
                    target.del_time = source.del_time,
                    target.del_by = source.del_by,
                    target.status_delsap = source.status_delsap,
                    target.otc_id = source.otc_id
                WHEN NOT MATCHED THEN
                    INSERT (
                        ot_id, 
                        ot_date, 
                        mk_nopeg,
                        ot_begin,
                        ot_end,
                        ot_end_sap,
                        kuota_terpakai_sp,
                        ot_wo_break,
                        ot_wo_break_begin,
                        ot_wo_break_end,
                        ot_ti1_status,
                        ot_ti1_begin,
                        ot_ti1_end,
                        ot_wo_break2,
                        ot_wo_break2_begin,
                        ot_wo_break2_end,
                        ot_ti2_status,
                        ot_ti2_begin,
                        ot_ti2_end,
                        ot_wo_break3,
                        ot_wo_break3_begin,
                        ot_wo_break3_end,
                        ot_ti3_status,
                        ot_ti3_begin,
                        ot_ti3_end,
                        ot_notes,
                        ot_app1_unit,
                        ot_app1_by,
                        ot_app1_time,
                        ot_app1_status,
                        ot_app2_unit,
                        ot_app2_by,
                        ot_app2_time,
                        ot_app2_status,
                        ot_app3_unit,
                        ot_app3_by,
                        ot_app3_time,
                        ot_app3_status,
                        ot_meal1_take_by,
                        ot_meal1_take_time,
                        ot_meal1_take_status,
                        ot_meal1_give_by,
                        ot_meal1_give_time,
                        ot_meal1_give_status,
                        ot_meal1_take_by2,
                        ot_meal1_rpt,
                        ot_meal2_take_by,
                        ot_meal2_take_time,
                        ot_meal2_take_status,
                        ot_meal2_give_by,
                        ot_meal2_give_time,
                        ot_meal2_give_status,
                        ot_meal2_take_by2,
                        ot_meal2_rpt,
                        ot_meal3_take_by,
                        ot_meal3_take_time,
                        ot_meal3_take_status,
                        ot_meal3_give_by,
                        ot_meal3_give_time,
                        ot_meal3_give_status,
                        ot_meal3_take_by2,
                        ot_meal3_rpt,
                        ot_create,
                        ot_createby,
                        ot_update,
                        ot_updateby,
                        status,
                        koreksi,
                        kunci,
                        status_sap,
                        del_flag,
                        del_time,
                        del_by,
                        status_delsap,
                        otc_id
                    ) 
                    VALUES (
                        source.ot_id, 
                        source.ot_date, 
                        source.mk_nopeg,
                        source.ot_begin,
                        source.ot_end,
                        source.ot_end_sap,
                        source.kuota_terpakai_sp,
                        source.ot_wo_break,
                        source.ot_wo_break_begin,
                        source.ot_wo_break_end,
                        source.ot_ti1_status,
                        source.ot_ti1_begin,
                        source.ot_ti1_end,
                        source.ot_wo_break2,
                        source.ot_wo_break2_begin,
                        source.ot_wo_break2_end,
                        source.ot_ti2_status,
                        source.ot_ti2_begin,
                        source.ot_ti2_end,
                        source.ot_wo_break3,
                        source.ot_wo_break3_begin,
                        source.ot_wo_break3_end,
                        source.ot_ti3_status,
                        source.ot_ti3_begin,
                        source.ot_ti3_end,
                        source.ot_notes,
                        source.ot_app1_unit,
                        source.ot_app1_by,
                        source.ot_app1_time,
                        source.ot_app1_status,
                        source.ot_app2_unit,
                        source.ot_app2_by,
                        source.ot_app2_time,
                        source.ot_app2_status,
                        source.ot_app3_unit,
                        source.ot_app3_by,
                        source.ot_app3_time,
                        source.ot_app3_status,
                        source.ot_meal1_take_by,
                        source.ot_meal1_take_time,
                        source.ot_meal1_take_status,
                        source.ot_meal1_give_by,
                        source.ot_meal1_give_time,
                        source.ot_meal1_give_status,
                        source.ot_meal1_take_by2,
                        source.ot_meal1_rpt,
                        source.ot_meal2_take_by,
                        source.ot_meal2_take_time,
                        source.ot_meal2_take_status,
                        source.ot_meal2_give_by,
                        source.ot_meal2_give_time,
                        source.ot_meal2_give_status,
                        source.ot_meal2_take_by2,
                        source.ot_meal2_rpt,
                        source.ot_meal3_take_by,
                        source.ot_meal3_take_time,
                        source.ot_meal3_take_status,
                        source.ot_meal3_give_by,
                        source.ot_meal3_give_time,
                        source.ot_meal3_give_status,
                        source.ot_meal3_take_by2,
                        source.ot_meal3_rpt,
                        source.ot_create,
                        source.ot_createby,
                        source.ot_update,
                        source.ot_updateby,
                        source.status,
                        source.koreksi,
                        source.kunci,
                        source.status_sap,
                        source.del_flag,
                        source.del_time,
                        source.del_by,
                        source.status_delsap,
                        source.otc_id
                    );
        ";
        $stmt = $sqlServerConn->prepare($upsertQuery);

        // Insert or update data in SQL Server
        foreach ($data as $row) {
            foreach ($row as $column => $value) {
                if($value != null && extract_date($value) !== false){
                    $date = extract_date($value);
                    if(!validate_date($date)){
                        $row[$column] = str_replace($date, '1900-01-25', $value);
                    }
                }
            }

            $current_id = $row['ot_id'];

            $stmt->execute([
                ':ot_id' => $row['ot_id'],
                ':ot_date' => $row['ot_date'] ?? '1900-01-25',
                ':mk_nopeg' => $row['mk_nopeg'],
                ':ot_begin' => $row['ot_begin'] ?? '1900-01-25 00:00:00',
                ':ot_end' => $row['ot_end'] ?? '1900-01-25 00:00:00',
                ':ot_end_sap' => $row['ot_end_sap'] ?? '1900-01-25 00:00:00',
                ':kuota_terpakai_sp' => $row['kuota_terpakai_sp'],
                ':ot_wo_break' => $row['ot_wo_break'],
                ':ot_wo_break_begin' => $row['ot_wo_break_begin'] ?? '00:00:00',
                ':ot_wo_break_end' => $row['ot_wo_break_end'] ?? '00:00:00',
                ':ot_ti1_status' => $row['ot_ti1_status'],
                ':ot_ti1_begin' => $row['ot_ti1_begin'] ?? '1900-01-25 00:00:00',
                ':ot_ti1_end' => $row['ot_ti1_end'] ?? '1900-01-25 00:00:00',
                ':ot_wo_break2' => $row['ot_wo_break2'],
                ':ot_wo_break2_begin' => $row['ot_wo_break2_begin'] ?? '00:00:00',
                ':ot_wo_break2_end' => $row['ot_wo_break2_end'] ?? '00:00:00',
                ':ot_ti2_status' => $row['ot_ti2_status'],
                ':ot_ti2_begin' => $row['ot_ti2_begin'] ?? '1900-01-25 00:00:00',
                ':ot_ti2_end' => $row['ot_ti2_end'] ?? '1900-01-25 00:00:00',
                ':ot_wo_break3' => $row['ot_wo_break3'],
                ':ot_wo_break3_begin' => $row['ot_wo_break3_begin'] ?? '00:00:00',
                ':ot_wo_break3_end' => $row['ot_wo_break3_end'] ?? '00:00:00',
                ':ot_ti3_status' => $row['ot_ti3_status'],
                ':ot_ti3_begin' => $row['ot_ti3_begin'] ?? '1900-01-25 00:00:00',
                ':ot_ti3_end' => $row['ot_ti3_end'] ?? '1900-01-25 00:00:00',
                ':ot_notes' => $row['ot_notes'],
                ':ot_app1_unit' => $row['ot_app1_unit'],
                ':ot_app1_by' => $row['ot_app1_by'],
                ':ot_app1_time' => $row['ot_app1_time'] ?? '1900-01-25 00:00:00',
                ':ot_app1_status' => $row['ot_app1_status'],
                ':ot_app2_unit' => $row['ot_app2_unit'],
                ':ot_app2_by' => $row['ot_app2_by'],
                ':ot_app2_time' => $row['ot_app2_time'] ?? '1900-01-25 00:00:00',
                ':ot_app2_status' => $row['ot_app2_status'],
                ':ot_app3_unit' => $row['ot_app3_unit'],
                ':ot_app3_by' => $row['ot_app3_by'],
                ':ot_app3_time' => $row['ot_app3_time'] ?? '1900-01-25 00:00:00',
                ':ot_app3_status' => $row['ot_app3_status'],
                ':ot_meal1_take_by' => $row['ot_meal1_take_by'],
                ':ot_meal1_take_time' => $row['ot_meal1_take_time'] ?? '1900-01-25 00:00:00',
                ':ot_meal1_take_status' => $row['ot_meal1_take_status'],
                ':ot_meal1_give_by' => $row['ot_meal1_give_by'],
                ':ot_meal1_give_time' => $row['ot_meal1_give_time'] ?? '1900-01-25 00:00:00',
                ':ot_meal1_give_status' => $row['ot_meal1_give_status'],
                ':ot_meal1_take_by2' => $row['ot_meal1_take_by2'],
                ':ot_meal1_rpt' => $row['ot_meal1_rpt'],
                ':ot_meal2_take_by' => $row['ot_meal2_take_by'],
                ':ot_meal2_take_time' => $row['ot_meal2_take_time'] ?? '1900-01-25 00:00:00',
                ':ot_meal2_take_status' => $row['ot_meal2_take_status'],
                ':ot_meal2_give_by' => $row['ot_meal2_give_by'],
                ':ot_meal2_give_time' => $row['ot_meal2_give_time'] ?? '1900-01-25 00:00:00',
                ':ot_meal2_give_status' => $row['ot_meal2_give_status'],
                ':ot_meal2_take_by2' => $row['ot_meal2_take_by2'],
                ':ot_meal2_rpt' => $row['ot_meal2_rpt'],
                ':ot_meal3_take_by' => $row['ot_meal3_take_by'],
                ':ot_meal3_take_time' => $row['ot_meal3_take_time'] ?? '1900-01-25 00:00:00',
                ':ot_meal3_take_status' => $row['ot_meal3_take_status'],
                ':ot_meal3_give_by' => $row['ot_meal3_give_by'],
                ':ot_meal3_give_time' => $row['ot_meal3_give_time'] ?? '1900-01-25 00:00:00',
                ':ot_meal3_give_status' => $row['ot_meal3_give_status'],
                ':ot_meal3_take_by2' => $row['ot_meal3_take_by2'],
                ':ot_meal3_rpt' => $row['ot_meal3_rpt'],
                ':ot_create' => $row['ot_create'] ?? '1900-01-25 00:00:00',
                ':ot_createby' => $row['ot_createby'],
                ':ot_update' => $row['ot_update'] ?? '1900-01-25 00:00:00',
                ':ot_updateby' => $row['ot_updateby'],
                ':status' => $row['status'],
                ':koreksi' => $row['koreksi'],
                ':kunci' => $row['kunci'],
                ':status_sap' => $row['status_sap'],
                ':del_flag' => $row['del_flag'],
                ':del_time' => $row['del_time'] ?? '1900-01-25 00:00:00',
                ':del_by' => $row['del_by'],
                ':status_delsap' => $row['status_delsap'],
                ':otc_id' => $row['otc_id']
            ]);
        }        

        $offset += $limit;

        echo ceil($offset/$limit) . '/' . ceil($total_data/$limit) . ' completed' . PHP_EOL;

    endwhile;

    echo "Data migration completed successfully, total ". $total_data . " data";

} catch (PDOException $e) {
    echo "Error: " . $e->getMessage() . '>> id: '. $current_id;
} finally {
    $mysqlConn = null;
    $sqlServerConn = null;
}


?>